#!/usr/bin/python3
def raise_exception_msg(message=""):
    try:
        print("C is fun")
    except NameError:
        print("C is fun")
